### ISSUE TITLE
Help to get it working

### ISSUE THREAD

**Issue by robson-gilli** [red-ant/angular-ra-pageload#1]
Hi, I came here throught this post (http://davidchin.me/blog/using-httpinterceptor-to-listen-for-page-load-event).

I´m trying to get it working but the event 'pageload:ready' isn't fired on my application. Do you have any other tutorial or a plunker demonstrating it's behavior?

Thanks
Robson

**Comment by davidchin** [comment]
Hey, have a look at http://jsfiddle.net/dyfchin/3a1updw0/

The example makes two ajax requests - requesting a JSON response and HTML response. After both requests are fulfilled, `pageload:ready` gets fired. You can see the result by inspecting your console.

It probably didn't fire for you because you didn't make any ajax request when you were testing this?

**Comment by robson-gilli** [comment]
Thank you for your time David.

The issue was that I had already another http interceptor at my app.config. I've made an ajustment on it and then your module started working like  a charm.

Thanks one more time.
